// PLAYER SHIT

freeslot("S_DASHCLOUD","SPR_DSHC","S_SMALLDASHCLOUD","S_CLOUDEFFECT","SPR_CLEF","sfx_pstep")

freeslot('sfx_mach1')
freeslot('sfx_mach2')
freeslot('sfx_mach3')
freeslot('sfx_mach4')

freeslot('sfx_pskid')
freeslot('sfx_drift')

freeslot('sfx_pgrab')

freeslot('SPR2_MAC2')
freeslot('SPR2_MAC3')
freeslot('SPR2_JUMT')
freeslot('SPR2_FALT')

freeslot('SPR2_PLAN')

freeslot('SPR2_DSPD')

freeslot('SPR2_SPDH')
freeslot('SPR2_SDHS')
freeslot('SPR2_SDHA')

freeslot('SPR2_LJTR')
freeslot('SPR2_LOJU')

freeslot('SPR2_HLST')
freeslot('SPR2_HLID')
freeslot('SPR2_HLFT')
freeslot('SPR2_HLFL')
freeslot('SPR2_HLLA')
freeslot('SPR2_HLWA')

freeslot('SPR2_BLSL')

freeslot('SPR2_WLCL')

freeslot('SPR2_CRTR')
freeslot('SPR2_CRCH')
freeslot('SPR2_CRAL')
freeslot('SPR2_CRFT')
freeslot('SPR2_CRFA')

freeslot('SPR2_PROL')
freeslot('SPR2_PRGU')

freeslot('SPR2_DIVE')

freeslot('SPR2_SJPR')
freeslot('SPR2_SJRE')
freeslot('SPR2_SJGO')
freeslot('SPR2_SJCS')
freeslot('SPR2_SJCA')

freeslot('SPR2_BSST')
freeslot('SPR2_BSFL')
freeslot('SPR2_BSLD')

freeslot('S_PEPPINO_JUMPTRNS')
freeslot('S_PEPPINO_FALLTRNS')

freeslot('S_PEPPINO_MACH1')
freeslot('S_PEPPINO_MACH2')
freeslot('S_PEPPINO_MACH3')
freeslot('S_PEPPINO_MACH4')

freeslot('S_PEPPINO_LAND')

freeslot('S_PEPPINO_SECONDJUMPTRNS')
freeslot('S_PEPPINO_SECONDJUMP')

freeslot('S_PEPPINO_MACH3JUMP')

freeslot('S_PEPPINO_MACH3HIT')

freeslot('S_PEPPINO_MACHSKIDTRNS')
freeslot('S_PEPPINO_MACHSKID')
freeslot('S_PEPPINO_MACHSKIDEND')

freeslot('S_PEPPINO_MACHDRIFTTRNS2')
freeslot('S_PEPPINO_MACHDRIFTTRNS3')

freeslot('S_PEPPINO_MACHDRIFT2')
freeslot('S_PEPPINO_MACHDRIFT3')

freeslot('S_PEPPINO_DASHPAD')

freeslot('S_PEPPINO_SUPLEXDASH')

freeslot('S_PEPPINO_AIRSUPLEXDASHTRNS')
freeslot('S_PEPPINO_AIRSUPLEXDASH')

freeslot('S_PEPPINO_LONGJUMPTRNS')
freeslot('S_PEPPINO_LONGJUMP')

freeslot('S_PEPPINO_HAULINGSTART')
freeslot('S_PEPPINO_HAULINGIDLE')
freeslot('S_PEPPINO_HAULINGFALLTRNS')
freeslot('S_PEPPINO_HAULINGFALL')
freeslot('S_PEPPINO_HAULINGLAND')
freeslot('S_PEPPINO_HAULINGWALK')

freeslot('S_PEPPINO_WALLCLIMB')

freeslot('S_PEPPINO_CROUCHTRNS')
freeslot('S_PEPPINO_CROUCH')
freeslot('S_PEPPINO_CROUCHWALK')
freeslot('S_PEPPINO_CROUCHFALLTRNS')
freeslot('S_PEPPINO_CROUCHFALL')

freeslot('S_PEPPINO_ROLL')
freeslot('S_PEPPINO_ROLLGETUP1')
freeslot('S_PEPPINO_ROLLGETUP2')
freeslot('S_PEPPINO_ROLLGETUP3')

freeslot('S_PEPPINO_DIVE')

freeslot('S_PEPPINO_SUPERJUMPSTARTTRNS')
freeslot('S_PEPPINO_SUPERJUMPSTART')
freeslot('S_PEPPINO_SUPERJUMP')
freeslot('S_PEPPINO_SUPERJUMPCANCELTRNS')
freeslot('S_PEPPINO_SUPERJUMPCANCEL')

freeslot('S_PEPPINO_BODYSLAMSTART')
freeslot('S_PEPPINO_BODYSLAM')
freeslot('S_PEPPINO_BODYSLAMLAND')

// call me lazy but no reason to type a shit ton of code when you can just
for i = 1,5 do
	freeslot('SPR2_FIB'..i)
	freeslot('S_PEPPINO_FINISHINGBLOW'..i)
end

freeslot('S_PEPPINO_BELLYSLIDE')

freeslot('S_NOISE_MACH3JUMP', 'S_NOISE_SECONDJUMPTRNS', 'S_NOISE_AIRSUPLEXDASHTRNS', 'S_NOISE_LONGJUMPTRNS', 'S_NOISE_HAULINGFALLTRNS', 'S_NOISE_HAULINGLAND', 'S_NOISE_CROUCHFALLTRNS', 'S_NOISE_JUMPTRNS')

sfxinfo[sfx_pstep].caption = "Step"
sfxinfo[sfx_mach1].caption = "Mach 1"
sfxinfo[sfx_mach2].caption = "Mach 2"
sfxinfo[sfx_mach3].caption = "Mach 3"
sfxinfo[sfx_mach4].caption = "Mach 4"
sfxinfo[sfx_pskid].caption = "Skid"
sfxinfo[sfx_drift].caption = "Drift"
sfxinfo[sfx_pgrab].caption = "Grab"


states[S_DASHCLOUD] = {
	sprite = SPR_DSHC,
	frame = A|FF_ANIMATE|FF_PAPERSPRITE,
	tics = 16,
	var1 = 8,
	var2 = 2,
	nextstate = S_DEATHSTATE
}

states[S_SMALLDASHCLOUD] = {
	sprite = SPR_SDSC,
	frame = A|FF_PAPERSPRITE|FF_ANIMATE,
	tics = 10,
	var1 = 5,
	var2 = 2,
	nextstate = S_DEATHSTATE
}

states[S_CLOUDEFFECT] = {
	sprite = SPR_CLEF,
	frame = A|FF_ANIMATE,
	tics = 28,
	var1 = 14,
	var2 = 2,
	nextstate = S_DEATHSTATE
}

states[S_PEPPINO_JUMPTRNS] = {SPR_PLAY, SPR2_JUMT|FF_ANIMATE|A, 6*2, nil, 5, 2, S_PLAY_SPRING}
states[S_NOISE_JUMPTRNS] = {SPR_PLAY, SPR2_JUMT|FF_ANIMATE|A, 10*2, nil, 9, 2, S_PLAY_SPRING}

states[S_PEPPINO_FALLTRNS] = {SPR_PLAY, SPR2_FALT, 4, nil, 0, 0, S_PLAY_FALL}

states[S_PEPPINO_LAND] = {SPR_PLAY, SPR2_PLAN|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PLAY_STND}

states[S_PEPPINO_MACH1] = {SPR_PLAY, SPR2_RUN_, 2, nil, 0, 0, S_PEPPINO_MACH1}
states[S_PEPPINO_MACH2] = {SPR_PLAY, SPR2_MAC2, 2, nil, 0, 0, S_PEPPINO_MACH2}
states[S_PEPPINO_MACH3] = {SPR_PLAY, SPR2_MAC3, 2, nil, 0, 0, S_PEPPINO_MACH3}
states[S_PEPPINO_MACH4] = {SPR_PLAY, SPR2_DASH, 2, nil, 0, 0, S_PEPPINO_MACH4}

states[S_PEPPINO_DASHPAD] = {SPR_PLAY, SPR2_DSPD|FF_ANIMATE|A, 8*2, nil, 7, 2, S_PEPPINO_MACH3}
states[S_PEPPINO_DASHPAD] = {SPR_PLAY, SPR2_DSPD|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_MACH3}

states[S_PEPPINO_SECONDJUMP] = {SPR_PLAY, SPR2_FLY_, 2, nil, 0, 0, S_PEPPINO_SECONDJUMP}
states[S_PEPPINO_SECONDJUMPTRNS] = {SPR_PLAY, SPR2_SPIN|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_SECONDJUMP}
states[S_NOISE_SECONDJUMPTRNS] = {SPR_PLAY, SPR2_SPIN|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_SECONDJUMP}

states[S_PEPPINO_MACH3JUMP] = {SPR_PLAY, SPR2_CLMB|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_MACH3}
states[S_NOISE_MACH3JUMP] = {SPR_PLAY, SPR2_CLMB|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_MACH3}

states[S_PEPPINO_MACH3HIT] = {SPR_PLAY, SPR2_SWIM|FF_ANIMATE|A, 5*2, nil, 4, 2, S_PEPPINO_MACH3}

states[S_PEPPINO_MACHSKIDTRNS] = {SPR_PLAY, SPR2_LAND|FF_ANIMATE|A, 7*2, nil, 6, 2, S_PEPPINO_MACHSKID}
states[S_PEPPINO_MACHSKID] = {SPR_PLAY, SPR2_MLEE, 2, nil, 0, 0, S_PEPPINO_MACHSKID}
states[S_PEPPINO_MACHSKIDEND] = {SPR_PLAY, SPR2_MLEL|FF_ANIMATE|A, 6*2, nil, 5, 2, S_PLAY_STND}

states[S_PEPPINO_MACHDRIFTTRNS2] = {SPR_PLAY, SPR2_TWIN|FF_ANIMATE|A, 11*2, nil, 10, 2, S_PEPPINO_MACHDRIFT2}
states[S_PEPPINO_MACHDRIFTTRNS3] = {SPR_PLAY, SPR2_BNCE|FF_ANIMATE|A, 13*2, nil, 12, 2, S_PEPPINO_MACHDRIFT3}

states[S_PEPPINO_MACHDRIFT2] = {SPR_PLAY, SPR2_FIRE, 2, nil, 0, 0, S_PEPPINO_MACHDRIFT2}
states[S_PEPPINO_MACHDRIFT3] = {SPR_PLAY, SPR2_FLT_, 2, nil, 0, 0, S_PEPPINO_MACHDRIFT3}

states[S_PEPPINO_SUPLEXDASH] = {SPR_PLAY, SPR2_SPDH, 2, nil, 0, 0, S_PEPPINO_SUPLEXDASH}

states[S_PEPPINO_AIRSUPLEXDASHTRNS] = {SPR_PLAY, SPR2_SDHS|FF_ANIMATE|A, 5*2, nil, 4, 2, S_PEPPINO_AIRSUPLEXDASH}
states[S_NOISE_AIRSUPLEXDASHTRNS] = {SPR_PLAY, SPR2_SDHS|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_AIRSUPLEXDASH}
states[S_PEPPINO_AIRSUPLEXDASH] = {SPR_PLAY, SPR2_SDHA, 2, nil, 0, 0, S_PEPPINO_AIRSUPLEXDASH}

states[S_PEPPINO_LONGJUMPTRNS] = {SPR_PLAY, SPR2_LJTR|FF_ANIMATE|A, 13*2, nil, 12, 2, S_PEPPINO_LONGJUMP}
states[S_NOISE_LONGJUMPTRNS] = {SPR_PLAY, SPR2_LJTR|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_LONGJUMP}
states[S_PEPPINO_LONGJUMP] = {SPR_PLAY, SPR2_LOJU, 2, nil, 0, 0, S_PEPPINO_LONGJUMP}

states[S_PEPPINO_HAULINGSTART] = {SPR_PLAY, SPR2_HLST|FF_ANIMATE|A, 5*2, nil, 4, 2, S_PEPPINO_HAULINGSTART}
states[S_PEPPINO_HAULINGIDLE] = {SPR_PLAY, SPR2_HLID, 2, nil, 0, 0, S_PEPPINO_HAULINGIDLE}
states[S_PEPPINO_HAULINGFALLTRNS] = {SPR_PLAY, SPR2_HLFT|FF_ANIMATE|A, 6*2, nil, 5, 2, S_PEPPINO_HAULINGFALL}
states[S_NOISE_HAULINGFALLTRNS] = {SPR_PLAY, SPR2_HLFT|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_HAULINGFALL}
states[S_PEPPINO_HAULINGFALL] = {SPR_PLAY, SPR2_HLFL, 2, nil, 0, 0, S_PEPPINO_HAULINGFALL}
states[S_PEPPINO_HAULINGLAND] = {SPR_PLAY, SPR2_HLLA|FF_ANIMATE|A, 5*2, nil, 4, 2, S_PEPPINO_HAULINGIDLE}
states[S_NOISE_HAULINGLAND] = {SPR_PLAY, SPR2_HLLA|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_HAULINGIDLE}
states[S_PEPPINO_HAULINGWALK] = {SPR_PLAY, SPR2_HLWA, 2, nil, 2, 2, S_PEPPINO_HAULINGWALK}

states[S_PEPPINO_CROUCH] = {SPR_PLAY, SPR2_CRCH, 2, nil, 2, 2, S_PEPPINO_CROUCH}
states[S_PEPPINO_CROUCHTRNS] = {SPR_PLAY, SPR2_CRCH, 3*2, nil, 2, 2, S_PEPPINO_CROUCH}
states[S_PEPPINO_CROUCHWALK] = {SPR_PLAY, SPR2_CRAL, 2, nil, 2, 2, S_PEPPINO_CROUCHWALK}
states[S_PEPPINO_CROUCHFALL] = {SPR_PLAY, SPR2_CRFA, 2, nil, 2, 2, S_PEPPINO_CROUCHFALL}
states[S_PEPPINO_CROUCHFALLTRNS] = {SPR_PLAY, SPR2_CRFT|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_CROUCHFALL}

states[S_NOISE_CROUCHFALLTRNS] = {SPR_PLAY, SPR2_CRFT|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PEPPINO_CROUCHFALL}

states[S_PEPPINO_ROLLGETUP1] = {SPR_PLAY, SPR2_PRGU|FF_ANIMATE|A, 12*2, nil, 11, 2, S_PEPPINO_MACH1}
states[S_PEPPINO_ROLLGETUP2] = {SPR_PLAY, SPR2_PRGU|FF_ANIMATE|A, 12*2, nil, 11, 2, S_PEPPINO_MACH2}
states[S_PEPPINO_ROLLGETUP3] = {SPR_PLAY, SPR2_PRGU|FF_ANIMATE|A, 12*2, nil, 11, 2, S_PEPPINO_MACH3}

states[S_PEPPINO_ROLL] = {SPR_PLAY, SPR2_PROL, 2, nil, 0, 0, S_PEPPINO_ROLL}

states[S_PEPPINO_DIVE] = {SPR_PLAY, SPR2_DIVE, 2, nil, 0, 0, S_PEPPINO_DIVE}

states[S_PEPPINO_BELLYSLIDE] = {SPR_PLAY, SPR2_BLSL, 2, nil, 0, 0, S_PEPPINO_BELLYSLIDE}
states[S_PEPPINO_WALLCLIMB] = {SPR_PLAY, SPR2_WLCL, 2, nil, 2, 2, S_PEPPINO_WALLCLIMB}

states[S_PEPPINO_SUPERJUMPSTARTTRNS] = {SPR_PLAY, SPR2_SJPR|FF_ANIMATE|A, 8*2, nil, 7, 2, S_PEPPINO_SUPERJUMPSTART}
states[S_PEPPINO_SUPERJUMPSTART] = {SPR_PLAY, SPR2_SJRE, 2, nil, 0, 0, S_PEPPINO_SUPERJUMPSTART}
states[S_PEPPINO_SUPERJUMP] = {SPR_PLAY, SPR2_SJGO, 2, nil, 0, 0, S_PEPPINO_SUPERJUMP}
states[S_PEPPINO_SUPERJUMPCANCELTRNS] = {SPR_PLAY, SPR2_SJCS|FF_ANIMATE|A, 13*2, nil, 12, 2, S_PEPPINO_SUPERJUMPCANCEL}
states[S_PEPPINO_SUPERJUMPCANCEL] = {SPR_PLAY, SPR2_SJCA, 2, nil, 0, 0, S_PEPPINO_SUPERJUMPCANCEL}

states[S_PEPPINO_BODYSLAMSTART] = {SPR_PLAY, SPR2_BSST|FF_ANIMATE|A, 9*2, nil, 8, 2, S_PEPPINO_BODYSLAM}
states[S_PEPPINO_BODYSLAM] = {SPR_PLAY, SPR2_BSFL, 2, nil, 0, 0, S_PEPPINO_BODYSLAM}
states[S_PEPPINO_BODYSLAMLAND] = {SPR_PLAY, SPR2_BSLD|FF_ANIMATE|A, 4*2, nil, 3, 2, S_PLAY_STND}

// unfortunately the same cant be applied here
states[S_PEPPINO_FINISHINGBLOW1] = {SPR_PLAY, SPR2_FIB1, 2, nil, 0, 0, S_PEPPINO_FINISHINGBLOW1}
states[S_PEPPINO_FINISHINGBLOW2] = {SPR_PLAY, SPR2_FIB2, 2, nil, 0, 0, S_PEPPINO_FINISHINGBLOW2}
states[S_PEPPINO_FINISHINGBLOW3] = {SPR_PLAY, SPR2_FIB3, 2, nil, 0, 0, S_PEPPINO_FINISHINGBLOW3}
states[S_PEPPINO_FINISHINGBLOW4] = {SPR_PLAY, SPR2_FIB4, 2, nil, 0, 0, S_PEPPINO_FINISHINGBLOW4}
states[S_PEPPINO_FINISHINGBLOW5] = {SPR_PLAY, SPR2_FIB5, 2, nil, 0, 0, S_PEPPINO_FINISHINGBLOW5}

// you may be wondering why im doing it like this
// surprisingly this is kinda how pt handles it lmfao
// atleast i think from how i looked at it

// SHIT FOR GRABBING

freeslot('MT_GRABBEDMOBJ')

mobjinfo[MT_GRABBEDMOBJ] = {
	doomednum = -1,
	spawnstate = S_PLAY_WAIT,
	flags = MF_NOGRAVITY
}

// MOBJ (EFFECTS, PARTICLES) SHIT

freeslot('MT_NTOPP_AFTERIMAGE')

freeslot('MT_LINEPARTICLE')
freeslot('MT_PARTICLE')

freeslot('S_LINEPARTICLE_MACHDUST')
freeslot('SPR_MCDS')

freeslot('S_LINEPARTICLE_RUNDUST')
freeslot('SPR_SDSC')

states[S_LINEPARTICLE_MACHDUST] = {SPR_MCDS, FF_PAPERSPRITE|FF_ANIMATE|A, 6*2, nil, 5, 2, S_NULL}
states[S_LINEPARTICLE_RUNDUST] = {SPR_SDSC, FF_PAPERSPRITE|FF_ANIMATE|A, 5*2, nil, 4, 2, S_NULL}

mobjinfo[MT_LINEPARTICLE] = {
	doomednum = -1,
	spawnstate = S_LINEPARTICLE_MACHDUST,
	flags = MF_NOCLIP|MF_NOBLOCKMAP|MF_NOCLIPHEIGHT|MF_NOGRAVITY
}

mobjinfo[MT_NTOPP_AFTERIMAGE] = {
	doomednum = -1,
	spawnstate = S_LINEPARTICLE_MACHDUST,
	flags = MF_NOCLIP|MF_NOBLOCKMAP|MF_NOCLIPHEIGHT|MF_NOGRAVITY
}